name = "image-uploader"
main = "src/index.ts"
compatibility_date = "2023-03-22"

[vars]
USER = "cr3vents"
PASS = "cr3v3nts!"
HOST = "https://image-uploader.crevents-images.workers.dev"

[env.production.vars]
HOST = "https://image-uploader.crevents-images.workers.dev"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'images'
preview_bucket_name = 'images'


