/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EventInterface extends ethers.utils.Interface {
  functions: {
    "addModerator(address,bool)": FunctionFragment;
    "changeEventDates(uint256,uint256,uint256)": FunctionFragment;
    "changeEventInfo(string,string,string,uint256)": FunctionFragment;
    "changeTicketPrices(uint256,uint256)": FunctionFragment;
    "changeWhitelistRoot(bytes32)": FunctionFragment;
    "checkIn(address)": FunctionFragment;
    "checkedParticipantCount()": FunctionFragment;
    "checkedParticipants(address)": FunctionFragment;
    "description()": FunctionFragment;
    "end()": FunctionFragment;
    "getEventInfo(uint256)": FunctionFragment;
    "getRegistrationOpen(uint256)": FunctionFragment;
    "link()": FunctionFragment;
    "maxParticipants()": FunctionFragment;
    "moderators(address)": FunctionFragment;
    "name()": FunctionFragment;
    "onlyWhitelistRegistration()": FunctionFragment;
    "owner()": FunctionFragment;
    "parentContractAddr()": FunctionFragment;
    "parentContractFee()": FunctionFragment;
    "participants(address)": FunctionFragment;
    "preSaleTicketPrice()": FunctionFragment;
    "publicRegister()": FunctionFragment;
    "registeredParticipantCount()": FunctionFragment;
    "registrationEnd()": FunctionFragment;
    "registrationOpen()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "start()": FunctionFragment;
    "ticketPrice()": FunctionFragment;
    "toggleRegistration(bool,bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelistRegister(bytes32[])": FunctionFragment;
    "whitelistRoot()": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addModerator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "changeEventDates",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeEventInfo",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeTicketPrices",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeWhitelistRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "checkIn", values: [string]): string;
  encodeFunctionData(
    functionFragment: "checkedParticipantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkedParticipants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "end", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEventInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationOpen",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "link", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxParticipants",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "moderators", values: [string]): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onlyWhitelistRegistration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parentContractAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "parentContractFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "preSaleTicketPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicRegister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registeredParticipantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registrationEnd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registrationOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "start", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ticketPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleRegistration",
    values: [boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistRegister",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addModerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeEventDates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeEventInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeTicketPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeWhitelistRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkedParticipantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "end", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "link", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moderators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onlyWhitelistRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parentContractAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parentContractFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preSaleTicketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredParticipantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ticketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "ParticipantChecked(address)": EventFragment;
    "ParticipantRegistered(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ParticipantChecked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ParticipantRegistered"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ParticipantCheckedEvent = TypedEvent<
  [string] & { participant: string }
>;

export type ParticipantRegisteredEvent = TypedEvent<
  [string] & { participant: string }
>;

export class Event extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EventInterface;

  functions: {
    addModerator(
      addr: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeEventDates(
      _start: BigNumberish,
      _end: BigNumberish,
      _registrationEnd: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeEventInfo(
      _name: string,
      _description: string,
      _link: string,
      _maxParticipants: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeTicketPrices(
      _ticketPrice: BigNumberish,
      _preSalePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeWhitelistRoot(
      rootHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkIn(
      participant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkedParticipantCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    checkedParticipants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    description(overrides?: CallOverrides): Promise<[string]>;

    end(overrides?: CallOverrides): Promise<[BigNumber]>;

    getEventInfo(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          boolean,
          boolean,
          boolean,
          string
        ] & {
          name: string;
          description: string;
          link: string;
          maxParticipants: BigNumber;
          registrationEnd: BigNumber;
          start: BigNumber;
          end: BigNumber;
          ticketPrice: BigNumber;
          preSaleTicketPrice: BigNumber;
          registeredParticipantCount: BigNumber;
          checkedParticipantCount: BigNumber;
          registrationOpen: boolean;
          onlyWhitelistRegistration: boolean;
          isRegistered: boolean;
          isChecked: boolean;
          addr: string;
        }
      ]
    >;

    getRegistrationOpen(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    link(overrides?: CallOverrides): Promise<[string]>;

    maxParticipants(overrides?: CallOverrides): Promise<[BigNumber]>;

    moderators(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    onlyWhitelistRegistration(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    parentContractAddr(overrides?: CallOverrides): Promise<[string]>;

    parentContractFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    participants(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    preSaleTicketPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicRegister(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registeredParticipantCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    registrationEnd(overrides?: CallOverrides): Promise<[BigNumber]>;

    registrationOpen(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    start(overrides?: CallOverrides): Promise<[BigNumber]>;

    ticketPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    toggleRegistration(
      _isOpen: boolean,
      _onlyWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whitelistRegister(
      _proof: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whitelistRoot(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addModerator(
    addr: string,
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeEventDates(
    _start: BigNumberish,
    _end: BigNumberish,
    _registrationEnd: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeEventInfo(
    _name: string,
    _description: string,
    _link: string,
    _maxParticipants: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeTicketPrices(
    _ticketPrice: BigNumberish,
    _preSalePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeWhitelistRoot(
    rootHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkIn(
    participant: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkedParticipantCount(overrides?: CallOverrides): Promise<BigNumber>;

  checkedParticipants(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  description(overrides?: CallOverrides): Promise<string>;

  end(overrides?: CallOverrides): Promise<BigNumber>;

  getEventInfo(
    currTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      boolean,
      boolean,
      boolean,
      string
    ] & {
      name: string;
      description: string;
      link: string;
      maxParticipants: BigNumber;
      registrationEnd: BigNumber;
      start: BigNumber;
      end: BigNumber;
      ticketPrice: BigNumber;
      preSaleTicketPrice: BigNumber;
      registeredParticipantCount: BigNumber;
      checkedParticipantCount: BigNumber;
      registrationOpen: boolean;
      onlyWhitelistRegistration: boolean;
      isRegistered: boolean;
      isChecked: boolean;
      addr: string;
    }
  >;

  getRegistrationOpen(
    currTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  link(overrides?: CallOverrides): Promise<string>;

  maxParticipants(overrides?: CallOverrides): Promise<BigNumber>;

  moderators(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  onlyWhitelistRegistration(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  parentContractAddr(overrides?: CallOverrides): Promise<string>;

  parentContractFee(overrides?: CallOverrides): Promise<BigNumber>;

  participants(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  preSaleTicketPrice(overrides?: CallOverrides): Promise<BigNumber>;

  publicRegister(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registeredParticipantCount(overrides?: CallOverrides): Promise<BigNumber>;

  registrationEnd(overrides?: CallOverrides): Promise<BigNumber>;

  registrationOpen(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  start(overrides?: CallOverrides): Promise<BigNumber>;

  ticketPrice(overrides?: CallOverrides): Promise<BigNumber>;

  toggleRegistration(
    _isOpen: boolean,
    _onlyWhitelist: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whitelistRegister(
    _proof: BytesLike[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whitelistRoot(overrides?: CallOverrides): Promise<string>;

  withdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addModerator(
      addr: string,
      status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    changeEventDates(
      _start: BigNumberish,
      _end: BigNumberish,
      _registrationEnd: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeEventInfo(
      _name: string,
      _description: string,
      _link: string,
      _maxParticipants: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeTicketPrices(
      _ticketPrice: BigNumberish,
      _preSalePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeWhitelistRoot(
      rootHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    checkIn(participant: string, overrides?: CallOverrides): Promise<void>;

    checkedParticipantCount(overrides?: CallOverrides): Promise<BigNumber>;

    checkedParticipants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    description(overrides?: CallOverrides): Promise<string>;

    end(overrides?: CallOverrides): Promise<BigNumber>;

    getEventInfo(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        name: string;
        description: string;
        link: string;
        maxParticipants: BigNumber;
        registrationEnd: BigNumber;
        start: BigNumber;
        end: BigNumber;
        ticketPrice: BigNumber;
        preSaleTicketPrice: BigNumber;
        registeredParticipantCount: BigNumber;
        checkedParticipantCount: BigNumber;
        registrationOpen: boolean;
        onlyWhitelistRegistration: boolean;
        isRegistered: boolean;
        isChecked: boolean;
        addr: string;
      }
    >;

    getRegistrationOpen(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    link(overrides?: CallOverrides): Promise<string>;

    maxParticipants(overrides?: CallOverrides): Promise<BigNumber>;

    moderators(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    onlyWhitelistRegistration(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    parentContractAddr(overrides?: CallOverrides): Promise<string>;

    parentContractFee(overrides?: CallOverrides): Promise<BigNumber>;

    participants(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    preSaleTicketPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicRegister(overrides?: CallOverrides): Promise<void>;

    registeredParticipantCount(overrides?: CallOverrides): Promise<BigNumber>;

    registrationEnd(overrides?: CallOverrides): Promise<BigNumber>;

    registrationOpen(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    start(overrides?: CallOverrides): Promise<BigNumber>;

    ticketPrice(overrides?: CallOverrides): Promise<BigNumber>;

    toggleRegistration(
      _isOpen: boolean,
      _onlyWhitelist: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistRegister(
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistRoot(overrides?: CallOverrides): Promise<string>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ParticipantChecked(address)"(
      participant?: null
    ): TypedEventFilter<[string], { participant: string }>;

    ParticipantChecked(
      participant?: null
    ): TypedEventFilter<[string], { participant: string }>;

    "ParticipantRegistered(address)"(
      participant?: null
    ): TypedEventFilter<[string], { participant: string }>;

    ParticipantRegistered(
      participant?: null
    ): TypedEventFilter<[string], { participant: string }>;
  };

  estimateGas: {
    addModerator(
      addr: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeEventDates(
      _start: BigNumberish,
      _end: BigNumberish,
      _registrationEnd: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeEventInfo(
      _name: string,
      _description: string,
      _link: string,
      _maxParticipants: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeTicketPrices(
      _ticketPrice: BigNumberish,
      _preSalePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeWhitelistRoot(
      rootHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkIn(
      participant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkedParticipantCount(overrides?: CallOverrides): Promise<BigNumber>;

    checkedParticipants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    description(overrides?: CallOverrides): Promise<BigNumber>;

    end(overrides?: CallOverrides): Promise<BigNumber>;

    getEventInfo(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRegistrationOpen(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    link(overrides?: CallOverrides): Promise<BigNumber>;

    maxParticipants(overrides?: CallOverrides): Promise<BigNumber>;

    moderators(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    onlyWhitelistRegistration(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    parentContractAddr(overrides?: CallOverrides): Promise<BigNumber>;

    parentContractFee(overrides?: CallOverrides): Promise<BigNumber>;

    participants(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    preSaleTicketPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicRegister(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registeredParticipantCount(overrides?: CallOverrides): Promise<BigNumber>;

    registrationEnd(overrides?: CallOverrides): Promise<BigNumber>;

    registrationOpen(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    start(overrides?: CallOverrides): Promise<BigNumber>;

    ticketPrice(overrides?: CallOverrides): Promise<BigNumber>;

    toggleRegistration(
      _isOpen: boolean,
      _onlyWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whitelistRegister(
      _proof: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whitelistRoot(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addModerator(
      addr: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeEventDates(
      _start: BigNumberish,
      _end: BigNumberish,
      _registrationEnd: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeEventInfo(
      _name: string,
      _description: string,
      _link: string,
      _maxParticipants: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeTicketPrices(
      _ticketPrice: BigNumberish,
      _preSalePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeWhitelistRoot(
      rootHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkIn(
      participant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkedParticipantCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkedParticipants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    description(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    end(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEventInfo(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRegistrationOpen(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    link(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxParticipants(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    moderators(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onlyWhitelistRegistration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    parentContractAddr(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parentContractFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    participants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    preSaleTicketPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicRegister(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registeredParticipantCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registrationEnd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registrationOpen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    start(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ticketPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toggleRegistration(
      _isOpen: boolean,
      _onlyWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whitelistRegister(
      _proof: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whitelistRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
